---
name: DBIx-Admin-CreateTable
version: 2.03
author:
  - 'Ron Savage <ron@savage.net.au>'
abstract: A module for creating and dropping tables and sequences
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Carp: 0
  DBI: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::Admin::CreateTable:
    file: lib/DBIx/Admin/CreateTable.pm
    version: 2.03
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
