---
abstract: 'A module for creating and dropping tables and sequences'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Admin-CreateTable
provides:
  DBIx::Admin::CreateTable:
    file: lib/DBIx/Admin/CreateTable.pm
    version: 2.07
requires:
  Carp: 0
  DBI: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 2.07
