---
abstract: 'Create and drop tables, primary indexes, and sequences'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Admin-CreateTable
provides:
  DBIx::Admin::CreateTable:
    file: lib/DBIx/Admin/CreateTable.pm
    version: 2.09
requires:
  DBI: 0
  Moo: 1.004002
  strict: 0
  warnings: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 2.09
